# Generated by Django 2.0.2 on 2018-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pr_logo', models.CharField(max_length=400)),
                ('pr_title', models.CharField(max_length=200)),
                ('pr_price', models.IntegerField()),
            ],
        ),
    ]
