# Generated by Django 2.0.2 on 2018-03-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pr_offer',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
