# Generated by Django 2.0.2 on 2018-03-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pr_logo',
        ),
    ]
